# Generated by Django 5.2.2 on 2025-07-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_group_module_alter_useractivitylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para URLs amigáveis', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
